spring.datasource.url=jdbc:mysql://zephyr.proxy.rlwy.net:52817/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=sgTBfoWmesCstCaXENrQnIixXvNHDlvK
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false


razorpay.key.id=rzp_test_SvTfQ9sqhM61NJ
razorpay.key.secret=DLvq5Z631HKjvJkCkyreRte2
server.port=${PORT:8080}