# ===== SERVER =====
server.port=${PORT:8080}

# ===== DATABASE =====
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3305}/${DB_NAME:ecommerce_db}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:Anuj@1811}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===== RAZORPAY =====
razorpay.key.id=${RAZORPAY_KEY_ID:rzp_test_SvTfQ9sqhM61NJ}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:DLvq5Z631HKjvJkCkyreRte2}